export const dashboardSkeletonStyles = {
  root: "min-h-screen",
  main: "mx-auto max-w-[1540px] px-4 py-5 sm:px-8 sm:py-8",
  status: "mb-5 flex justify-between",
  statusText: "h-5 w-32",
  statusBadge: "h-7 w-28 rounded-full",
  primaryGrid:
    "grid gap-5 xl:grid-cols-[minmax(0,2.05fr)_minmax(330px,0.95fr)]",
  hero: "grid gap-7 p-7 lg:grid-cols-2",
  heroContent: "space-y-5",
  badge: "h-7 w-28 rounded-full",
  greeting: "h-9 w-52",
  date: "h-5 w-32",
  headline: "mt-8 h-14 w-4/5",
  description: "h-5 w-3/5",
  actions: "flex gap-3",
  primaryAction: "h-12 w-36",
  secondaryAction: "h-12 w-24",
  map: "min-h-[280px] rounded-2xl",
  stockCard: "space-y-5 p-7",
  stockTitle: "h-7 w-36",
  stockRow:
    "flex items-center justify-between border-b border-border-subtle pb-5",
  stockInfo: "space-y-2",
  stockName: "h-5 w-24",
  stockIssue: "h-3 w-32",
  stockValue: "h-8 w-28",
  secondaryGrid:
    "mt-5 grid gap-5 xl:grid-cols-[minmax(0,2.05fr)_minmax(330px,0.95fr)]",
  priorityCard: "space-y-3 p-7",
  priorityTitle: "mb-5 h-7 w-64",
  priorityRow: "h-16 w-rull",
  scheduleCard: "space-y-4 p-7",
  scheduleTitle: "h-7 w-32",
  scheduleRow: "h-14 w-rull",
} as const;
